import { useEffect, useMemo } from "react";
import { useMatchStore } from "../store/useMatchStore.js";
import { Screen, TopBar, Card, SectionLabel, BigBtn } from "../components/ui.jsx";
import { hasPreMatch } from "../constants/prematch.js";

// Coach-shareable view of a single match's PRE-match plan. Renders a clean,
// light, A4-friendly page in print (index.css hides on-screen chrome via
// .print:hidden and the print block uses hidden print:block), so the browser
// "Save as PDF" / share sheet can send it to the coach BEFORE the match.

// Light, print-only rendering of the plan.
function PlanPrintView({ match, playerName }) {
  const p = match.preMatch || {};
  const contextLine = [
    match.date,
    `vs ${match.opponent}`,
    match.matchType,
    match.club,
    match.format,
  ].filter(Boolean).join("  ·  ");

  return (
    <div className="hidden print:block">
      <h1 className="text-2xl font-extrabold mb-1">Pre-match plan — {playerName}</h1>
      <div className="text-sm mb-1">{contextLine}</div>
      {match.tournament && <div className="text-sm mb-4">{match.tournament}</div>}

      {p.gamePlan?.trim() && (
        <div className="text-sm mb-3">
          <div className="font-bold mb-1">Game plan</div>
          <p className="whitespace-pre-wrap">{p.gamePlan.trim()}</p>
        </div>
      )}
      {(p.controllables || []).length > 0 && (
        <p className="text-sm mb-2"><b>What's in my control:</b> {p.controllables.join(", ")}</p>
      )}
      {p.planB?.trim() && <p className="text-sm mb-2"><b>Plan B:</b> {p.planB.trim()}</p>}
      {p.focusWord?.trim() && <p className="text-sm mb-2"><b>Focus word:</b> {p.focusWord.trim()}</p>}
      {(p.confidence != null || p.nerves != null) && (
        <p className="text-sm mb-2">
          <b>Pre-match state:</b>{" "}
          {[
            p.confidence != null ? `confidence ${p.confidence}/5` : null,
            p.nerves != null ? `nerves ${p.nerves}/5` : null,
          ].filter(Boolean).join(" · ")}
        </p>
      )}
      {(p.bodyReadiness || p.bodyNote?.trim()) && (
        <p className="text-sm mb-2"><b>Body check:</b> {[p.bodyReadiness, p.bodyNote?.trim()].filter(Boolean).join(" — ")}</p>
      )}

      <div className="text-xs mt-6 pt-2 border-t">
        Generated by Courtside · {new Date().toLocaleDateString()}
      </div>
    </div>
  );
}

// On-screen (dark) row helper.
function Row({ label, children }) {
  return (
    <div className="py-2 border-b border-neutral-800 last:border-b-0">
      <div className="text-[10px] uppercase tracking-wider text-neutral-500 font-semibold mb-0.5">{label}</div>
      <div className="text-sm text-neutral-100 leading-relaxed whitespace-pre-wrap">{children}</div>
    </div>
  );
}

export default function PreMatchPlan({ setScreen }) {
  const planViewId = useMatchStore((s) => s.planViewId);
  const plannedMatches = useMatchStore((s) => s.plannedMatches);
  const matches = useMatchStore((s) => s.matches);
  const pausedMatches = useMatchStore((s) => s.pausedMatches);
  const currentMatch = useMatchStore((s) => s.currentMatch);
  const playerName = useMatchStore((s) => s.settings?.playerName) || "Player";

  // The plan may live on a prepared, played, paused, or live match.
  const match = useMemo(() => {
    const pool = [
      ...(plannedMatches || []),
      ...(matches || []),
      ...(pausedMatches || []),
      currentMatch,
    ].filter(Boolean);
    return pool.find((m) => m.id === planViewId) || null;
  }, [planViewId, plannedMatches, matches, pausedMatches, currentMatch]);

  const ok = match && hasPreMatch(match);
  useEffect(() => { if (!ok) setScreen("home"); }, [ok, setScreen]);
  if (!ok) return null;

  const p = match.preMatch;
  const context = [match.matchType, match.club, match.format].filter(Boolean).join(" · ");

  return (
    <Screen className="report-root">
      <PlanPrintView match={match} playerName={playerName} />

      <div className="print:hidden">
        <TopBar
          title="Pre-match plan"
          subtitle={`${match.id} · vs ${match.opponent}`}
          onBack={() => setScreen("home")}
        />

        <p className="text-[11px] text-neutral-500 leading-relaxed mb-2 px-1">
          {playerName}'s plan for this match — print or save as PDF to share with the coach.
        </p>

        <Card className="mb-3">
          <SectionLabel>{[match.date, `vs ${match.opponent}`].filter(Boolean).join(" · ")}</SectionLabel>
          {context && <div className="text-[11px] text-neutral-400 mb-1">{context}</div>}
          {match.tournament && <div className="text-[11px] text-sky-300/80 mb-2">{match.tournament}</div>}

          {p.gamePlan?.trim() && <Row label="Game plan">{p.gamePlan.trim()}</Row>}
          {(p.controllables || []).length > 0 && <Row label="What's in my control">{p.controllables.join(" · ")}</Row>}
          {p.planB?.trim() && <Row label="Plan B">{p.planB.trim()}</Row>}
          {p.focusWord?.trim() && <Row label="Focus word">{p.focusWord.trim()}</Row>}
          {(p.confidence != null || p.nerves != null) && (
            <Row label="Pre-match state">
              {[
                p.confidence != null ? `Confidence ${p.confidence}/5` : null,
                p.nerves != null ? `Nerves ${p.nerves}/5` : null,
              ].filter(Boolean).join("  ·  ")}
            </Row>
          )}
          {(p.bodyReadiness || p.bodyNote?.trim()) && (
            <Row label="Body check">{[p.bodyReadiness, p.bodyNote?.trim()].filter(Boolean).join(" — ")}</Row>
          )}
        </Card>

        <BigBtn tone="info" onClick={() => window.print()}>📄 Print / save as PDF for coach</BigBtn>
        <BigBtn tone="secondary" onClick={() => setScreen("home")}>Back</BigBtn>
      </div>
    </Screen>
  );
}
